before_install:
  - chmod +x KT-34751/gradlew
  - chmod +x KT-34756/gradlew
  - chmod +x KT-34832/gradlew
  - chmod +x KT-34946/gradlew
script:
  - cd KT-34751
  - ./gradlew clean build
  - cd ..
  - cd KT-34756
  - ./gradlew clean build
  - cd ..
  - cd KT-34832
  - ./gradlew clean build
  - cd ..
  - cd KT-34946
  - ./gradlew clean build
  - cd ..
notifications:
  email: false